version: '3'
services:
  influxdb:
    image: influxdb:1.8-alpine
    ports:
      - '127.0.0.1:8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME:-admin}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD:-admin}
  chronograf:
    image: chronograf:latest
    ports:
      - '127.0.0.1:8888:8888'
    volumes:
      - chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME:-admin}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD:-admin}
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
  receiver:
    build: receiver/
    ports:
      - '5000:5000'
    volumes:
      - ./receiver/:/usr/src/app
    depends_on:
      - influxdb
    environment:
      - INFLUX_HOST=influxdb

volumes:
  influxdb-storage:
  chronograf-storage:
  grafana-storage:
